/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_unicorn_faces_app_natives_FaceDetector */

#ifndef _Included_com_unicorn_faces_app_natives_FaceDetector
#define _Included_com_unicorn_faces_app_natives_FaceDetector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_unicorn_faces_app_natives_FaceDetector
 * Method:    load
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_unicorn_faces_app_natives_FaceDetector_load
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_unicorn_faces_app_natives_FaceDetector
 * Method:    empty
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_unicorn_faces_app_natives_FaceDetector_empty
  (JNIEnv *, jobject);

/*
 * Class:     com_unicorn_faces_app_natives_FaceDetector
 * Method:    findFaces
 * Signature: ([BII)[Lcom/unicorn/faces/app/natives/FaceDetector/Face;
 */
JNIEXPORT jobjectArray JNICALL Java_com_unicorn_faces_app_natives_FaceDetector_findFaces
  (JNIEnv *, jobject, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
