/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class FaceDetector */

#ifndef _Included_FaceDetector
#define _Included_FaceDetector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     FaceDetector
 * Method:    load
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_FaceDetector_load
  (JNIEnv *, jclass, jstring);

/*
 * Class:     FaceDetector
 * Method:    findFaces
 * Signature: ([BII)[LFaceDetector/Face;
 */
JNIEXPORT jobjectArray JNICALL Java_FaceDetector_findFaces
  (JNIEnv *, jclass, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
